### ISSUE TITLE
Erreur avec le mot « syndicaux »

### ISSUE THREAD

**Issue by LightBeamOvHe** [leoncik/Parafaute#10]
Bonjour
Tout d'abord, merci beaucoup pour le travail fourni sur cette extension. Je souhaitais signaler une erreur, il semblerait que l'extension ai un problème avec le mot « syndicaux » comme constaté sur cette page : https://gitlab.com/stop-ecriture-inclusive/stop-ecriture-inclusive/-/blob/master/example.md
C'est un exemple fourni par une autre extension mais vu que l'écriture inclusive change pas selon les extensions ....
Avec Parafaute, on voit que syndicaux est écrit syndicauxs, on dirait que l'extension comprend que syndicaux est au pluriel, mais rajoute un s quand même à la fin.

Voilà c'était juste pour signaler cette toute petite coquille, encore merci

**Comment by leoncik** [comment]
Bonjour,
Merci pour votre commentaire et votre rapport d'erreur.
Je viens de corriger le problème et le correctif sera bientôt visible dans la version 2.0.3 de l'extension ;-)
