### ISSUE TITLE
Trophées Reddit pas corrigés sur le menu de droite (écriture inclusive)

### ISSUE THREAD

**Issue by LightBeamOvHe** [leoncik/Parafaute#13]
Bonjour,

J'ai remarqué que sur Reddit, le menu à droite n'était pas corrigé, par exemple : 
![image](https://github.com/user-attachments/assets/d5383bf4-f8eb-4835-acab-4d8766bf7bd2)
J'ai Reddit Enhancer mais j'ai essayé même en désactivant cette extension, et c'est toujours affiché de cette manière.
J'ai cependant vérifié et cela semble fonctionner sur le reste du site, notamment lorsque les trophées sont affichés sous le pseudo d'une personne, par exemple : 
![image](https://github.com/user-attachments/assets/2c2aad44-f2fe-4caf-9060-592129a1622d)
Cette personne a un trophée sous son pseudo lorsqu'elle commente et Parafaute fonctionne correctement.
Pour info, j'ai évidemment coché la case pour activer l'extension sur les sites non francophones.
Merci beaucoup pour votre travail :)

**Comment by leoncik** [comment]
Bonsoir,

Merci pour ce gentil commentaire et ce rapport détaillé.
Le problème venait du fait qu'il manquant la gestion des finales en « ier » dans mon dictionnaire. 

C'est maintenant ajouté et cela sera prochainement actif dans la version 2.0.4 de l'extension.
